---
title: "First Blog post!"
description:
author:
  - name: Aidan Berg 
    url: aidanberg.us
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hello,

This is the first post in my blog, and either you've caught me very early in the development of my professional website, or you've scrolled down too far. Either way, you are witnessing the ultimate achievement of an amatuer HTML coder, and the peak of technology prior to video streaming: a blog. While they are somewhat outdated, the google search engine still caters to them, and I need a place to cultivate my portfolio a little more cleanly, since the previous strategy of hoping my ancient laptop's would survive forever is failing quite badly.

Either way, in the next few weeks I intend to do a lengthy writeup abouta  dataset I will pull -- I like to talk a lot about my *ggplot* skills, but since I feel a smidge unethical showing off my charts from work, I will instead write-up my own projcet and see if I can't make some fun charts to demonstrate that I can, in fact, use *ggplot*




