project:
  type: website

website:
  title: "Aidan Berg's Blog"
  site-path: https://aidanberg.us/blog/
  description: "Learning R and exploring data science"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
      - href: https://www.linkedin.com/in/aidan-berg-epi/
      - icon: rss
      - href: index.xml

format:
  html:
    theme: litera
    css: styles.css

editor: visual

