project:
  type: website

website:
  title: "Aidan Berg's Blog"
  site-url: https://aidanberg.us/blog/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Aidan-Berg
      - icon: linkedin
        href: https://www.linkedin.com/in/aidan-berg-epi/
      - icon: rss
      - href: index.yml
format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

